config/routes.rb
Rails.application.routes.draw do
  resources :microsposts

  resources :users
  root 'users#index'

end

app/models/microspost.rb
class Microspost < ActiveRecord::Base
	belongs_to :user
	validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microsposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/microsposts_controller.rb
class MicrospostsController < ApplicationController
  before_action :set_microspost, only: [:show, :edit, :update, :destroy]

  # GET /microsposts
  # GET /microsposts.json
  def index
    @microsposts = Microspost.all
  end

  # GET /microsposts/1
  # GET /microsposts/1.json
  def show
  end

  # GET /microsposts/new
  def new
    @microspost = Microspost.new
  end

  # GET /microsposts/1/edit
  def edit
  end

  # POST /microsposts
  # POST /microsposts.json
  def create
    @microspost = Microspost.new(microspost_params)

    respond_to do |format|
      if @microspost.save
        format.html { redirect_to @microspost, notice: 'Microspost was successfully created.' }
        format.json { render :show, status: :created, location: @microspost }
      else
        format.html { render :new }
        format.json { render json: @microspost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microsposts/1
  # PATCH/PUT /microsposts/1.json
  def update
    respond_to do |format|
      if @microspost.update(microspost_params)
        format.html { redirect_to @microspost, notice: 'Microspost was successfully updated.' }
        format.json { render :show, status: :ok, location: @microspost }
      else
        format.html { render :edit }
        format.json { render json: @microspost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microsposts/1
  # DELETE /microsposts/1.json
  def destroy
    @microspost.destroy
    respond_to do |format|
      format.html { redirect_to microsposts_url, notice: 'Microspost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microspost
      @microspost = Microspost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def microspost_params
      params.require(:microspost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @microsposts = Microspost.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microsposts_helper.rb
module MicrospostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/microsposts/_form.html.erb
<%= form_for(@microspost) do |f| %>
  <% if @microspost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@microspost.errors.count, "error") %> prohibited this microspost from being saved:</h2>

      <ul>
      <% @microspost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microsposts/edit.html.erb
<h1>Editing microspost</h1>

<%= render 'form' %>

<%= link_to 'Show', @microspost %> |
<%= link_to 'Back', microsposts_path %>

app/views/microsposts/index.html.erb
<h1>Listing microsposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microsposts.each do |microspost| %>
      <tr>
        <td><%= microspost.content %></td>
        <td><%= microspost.user_id %></td>
        <td><%= link_to 'Show', microspost %></td>
        <td><%= link_to 'Edit', edit_microspost_path(microspost) %></td>
        <td><%= link_to 'Destroy', microspost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Microspost', new_microspost_path %>

app/views/microsposts/new.html.erb
<h1>New microspost</h1>

<%= render 'form' %>

<%= link_to 'Back', microsposts_path %>

app/views/microsposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @microspost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @microspost.user_id %>
</p>

<%= link_to 'Edit', edit_microspost_path(@microspost) %> |
<%= link_to 'Back', microsposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<hr width=500>

<% @microsposts.each do |microspost| %>
	<p><%= microspost.content %></p>

<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>